<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework Condition="'$(VesperaTargetFramework)' == ''">net8.0</TargetFramework>
    <TargetFramework Condition="'$(VesperaTargetFramework)' != ''">$(VesperaTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <LangVersion>latest</LangVersion>
    <AssemblyName>Vespera.NET</AssemblyName>
    <RootNamespace>Vespera</RootNamespace>
  </PropertyGroup>
</Project>
